### ISSUE TITLE
Allow and sanitize iframe for markdown-it-video plugin

### ISSUE THREAD

**Issue by changeweb** [svbergerem/markdown-it-sanitizer#1]
I want to use both `markdown-it-sanitizer` and `markdown-it-video` plugins. But  it requires iframe to embed youtube video. I think `markdown-it-sanitizer` should be compatible with other `markdown-it` plugins.

**Comment by svbergerem** [comment]
@changeweb Did you try to use both? markdown-it-sanitizer only goes through `html_block` and `html_inline` states while markdown-it-video uses `video` states. I didn't try it yet but to me it looks like markdown-it-sanitizer is already compatible with markdown-it-video.

**Comment by svbergerem** [comment]
I just added the tests from markdown-it-video to this repo. Since all tests pass I'll close this issue.
