### ISSUE TITLE
IMG regex allows no other attributes before SRC

### ISSUE THREAD

**Issue by hallvors** [svbergerem/markdown-it-sanitizer#4]
The regular expression used to detect IMG tags:

```
'<img\\ssrc="([^"<>]*)"(?:\\salt="([^"<>]*)")?(?:\\stitle="([^"<>]*)")?\\s?\\/?>';
```

https://github.com/svbergerem/markdown-it-sanitizer/blob/master/index.js#L42

This regular expression creates inconsistent results, for example if you sanitize markup containing 

```
<img src="http://foo.." alt="image 1">
<img alt="image 2" src="http://foo..">
```

One will show up as an image and one as markup :/

**Comment by svbergerem** [comment]
I just released a new version which allows arbitrary attributes for image tags, but only keeps `src`, `alt` and `title` attributes.

**Comment by hallvors** [comment]
Thanks a lot! :)
