### ISSUE TITLE
Specify whitelist elements?

### ISSUE THREAD

**Issue by CalebKester** [svbergerem/markdown-it-sanitizer#6]
Without going into the plugin is there anyway to pass whitelist elements? 

Sepcifically I need to whitelist tables (need col/rowspan support).

**Comment by svbergerem** [comment]
Related to #5. Currently this is not possible.

**Comment by CalebKester** [comment]
Makes sense. I'll go ahead and close this as it looks like that one is a better tracker of it.

Thanks,
